services:
  - type: web
    name: vroom-laravel
    env: docker
    repo: https://github.com/Ivontsoa-Gracia/mini-projet.git
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:xxxxxxxxxxxxxx
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-cvd7putsvqrc73ee14ug-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: miniprojet_bd
      - key: DB_USERNAME
        value: laravel_user
      - key: DB_PASSWORD
        value: 8T3mWCxxjMPaLL6RBUAbnaR1ZZf3NOzs
