services:
  - type: web
    name: vroom-laravel
    env: docker
    repo: https://github.com/Ivontsoa-Gracia/tsidika.git
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:xxxxxxxxxxxxxx
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-cvd9nmjv2p9s73ccvn40-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: miniprojet_bd_bf6z
      - key: DB_USERNAME
        value: laravel_user
      - key: DB_PASSWORD
        value: iURhoKZBBYJeSx69Sbea7buAVqAMZOcv
